name: Build docker image

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy application
        run: docker build -t my-app .
